CC := gcc

single_conn_client: single_conn_client.c
	-$(CC) -o $@ $^

single_conn_server: single_conn_server.c
	-$(CC) -o $@ $^

multi_conn_client: multi_conn_client.c
	-$(CC) -o $@ $^

multi_conn_server: multi_conn_server.c
	-$(CC) -o $@ $^

udp_client: udp_client.c
	-$(CC) -o $@ $^

udp_server: udp_server.c
	-$(CC) -o $@ $^

ipc_test: ipc_test.c
	-$(CC) -o $@ $^